### ISSUE TITLE
求DMInstall.bin文件，lfs拉不下来

### ISSUE THREAD

**Issue by qinchz** [helsonxiao/docker-dm#1]
fetch: Fetching reference refs/heads/master
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.         
error: failed to fetch some objects from 'https://github.com/helsonxiao/docker-dm.git/info/lfs'

**Comment by helsonxiao** [comment]
不好意思，这些文件我本地也没有存档，你可以从达梦数据库官网下载，也可以联系他们的客服索取。他们的最新版可能也支持 Docker 了。

**Comment by qinchz** [comment]
好的，谢谢。我找下文件，官网貌似没出arm64架构的docker包

**Comment by helsonxiao** [comment]
可以找他们技术客服要（电话/社区/...），藏得是很深。
